version: "2"
services:
  node:
    build: .
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "172.17.0.1:8090:8080"
      - "8077:8080"
    command: "./dist/jsbattle.js -h=0.0.0.0 start"
